version: '3.12'

services:
  sentiment-app:
    build: .
    container_name: twitter_sentiment_container
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - TF_ENABLE_ONEDNN_OPTS=0
    restart: always